server:
  port: 8282

spring:
  application:
    name: STORE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

