spring:
  application:
    name: AUTHENTICATION-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 9898